-- Tiny Inline Diagnostic - Modern inline diagnostics
-- DESABILITADO: Para habilitar, descomente o return abaixo e comente o return {}
return {}

-- return {
--   'rachartier/tiny-inline-diagnostic.nvim',
--   event = 'LspAttach',
--   config = function()
--     require('tiny-inline-diagnostic').setup {
--       preset = 'modern',
--       options = {
--         show_source = true,
--         throttle = 20,
--         softwrap = 30,
--         multiple_diag_under_cursor = true,
--         multilines = true,
--         show_all_diags_on_cursorline = true,
--         enable_on_insert = false,
--         overflow = {
--           mode = 'wrap',
--         },
--       },
--     }
--     
--     -- Lembre-se de desabilitar virtual_text em lua/config/lsp.lua quando habilitar este plugin
--     -- vim.diagnostic.config({ virtual_text = false })
--   end,
-- }
