-- Intelephense PHP Language Server configuration
return {
  cmd = { 'intelephense', '--stdio' },
  filetypes = { 'php' },
  root_markers = { 'composer.json', '.git' },
  settings = {
    intelephense = {
      stubs = {
        'bcmath',
        'bz2',
        'calendar',
        'Core',
        'curl',
        'date',
        'dba',
        'dom',
        'enchant',
        'fileinfo',
        'filter',
        'ftp',
        'gd',
        'gettext',
        'hash',
        'iconv',
        'imap',
        'intl',
        'json',
        'ldap',
        'libxml',
        'mbstring',
        'mcrypt',
        'mysql',
        'mysqli',
        'password',
        'pcntl',
        'pcre',
        'PDO',
        'pdo_mysql',
        'Phar',
        'readline',
        'recode',
        'Reflection',
        'regex',
        'session',
        'SimpleXML',
        'soap',
        'sockets',
        'sodium',
        'SPL',
        'standard',
        'superglobals',
        'sysvsem',
        'sysvshm',
        'tokenizer',
        'xml',
        'xdebug',
        'xmlreader',
        'xmlwriter',
        'yaml',
        'zip',
        'zlib',
        'wordpress',
        'woocommerce',
        'acf-pro',
        'wordpress-globals',
        'wp-cli',
        'openssl',
        'random',
      },
      environment = {
        phpVersion = '8.4',
      },
      files = {
        maxSize = 1000000,
      },
      diagnostics = {
        undefinedVariables = true,
        undefinedFunctions = true,
        undefinedConstants = true,
        undefinedClassConstants = true,
        undefinedMethods = true,
        undefinedProperties = true,
        undefinedTypes = true,
      },
    },
  },
  capabilities = vim.lsp.protocol.make_client_capabilities(),
}
